### ISSUE TITLE
Remove Plots.jl dependency

### ISSUE THREAD

**Issue by juliohm** [sefffal/PairPlots.jl#1]
If this is really a plot recipe, it shouldn't have Plots.jl as a dependency. Other packages cannot depend on PairPlots.jl otherwise.

**Comment by sefffal** [comment]
The version I submitted to the registry does not, but it’s a tough choice to make. Some important functionality does not exist in RecipesBase. First and foremost, the `bbox` function has no alternative that I’m aware of for defining custom layouts. (Suggestion on workarounds welcome).

I would be happy to place Plots behind Requires though instead of a direct dependency. Would that help?

**Comment by sefffal** [comment]
Latest tagged version does not depend directly on Plots, and accesses the necessary `bbox` function through Requires.
Technically, this is not a plot recipe, but I think this still solves the main issue?

**Comment by juliohm** [comment]
I will close the issue. Keep in mind that Requires.jl is a bad idea. It increases load time and you cannot control the version of your dependency on Plots.jl. So if someone changes the bbox feature you are using in a way that breaks your code, you will only know if you try to run it.

**Comment by sefffal** [comment]
I do see your points. What if I were to create a tiny PairPlotsBase for other upstream packages to depend on, and then directly depend on Plots?

**Comment by juliohm** [comment]
This seems to be an unnecessarily complicated solution for what should be a recipe package in the first place? The major advantage of the plotting ecosystem in Julia is being able to compose advanced plots from basic recipes. I don't think a PairPlotsBase.jl makes sense.

**Comment by sefffal** [comment]
I agree, but if the layout tools aren't in RecipesBase, then I just don't see a way to make this a recipe.

I guess the ultimate solution is to push the plots maintainers to expose that functionality.
