### ISSUE TITLE
ERROR: Unsatisfiable requirements detected for package PairPlots

### ISSUE THREAD

**Issue by rczerminski-valo** [sefffal/PairPlots.jl#5]
```
julia> pkg"add PairPlots"
Resolving package versions...
ERROR: Unsatisfiable requirements detected for package PairPlots [43a3c2be]:
[...]
```
for
```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
julia>
```
Is this an user error? I would appreciate any suggestions - PairPlots pkg looks very promising!

**Comment by sefffal** [comment]
Hi @rczerminski-valo,
Thanks for filing this issue. I think this l error means there is some PairPlots is not compatible with another package you have installed in your environment.
Probably I have one of the version constraints set too restrictively in PairPlots.

Would you mind providing the full error message above from when you tried to add the package?

The other thing that would be useful is to try adding the package in a clean environment (e.g. `activate PairPlotsTest` first). This can help us rule out other problems.

thanks!

**Comment by sefffal** [comment]
@rczerminski-valo yes there is! You just need to pass two options:
```julia
PairPlots.corner(table, plotcontours=false, filterscatter=false)
```

And you'll get a plot like this:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/7330605/146046302-b9c40ee4-470b-4a6e-aada-c74c78e42404.png">

If you want to control the marker appearance, you can pass a named tuple of keyword arguments for the `scatter` call:
```julia
PairPlots.corner(table, plotcontours=false, filterscatter=false, scatter_kwargs=(;markersize=3, color=:red))
```

If you do, make sure to use the fully qualified keywords from Plots instead of short-hands like `ms=3`.

**Comment by sefffal** [comment]
Closing the issue now, but feel free to open more if you have any questions or something isn't documented.
