### ISSUE TITLE
Consider renaming `PairPlots.Correlation` to `PairPlots.PearsonCorrelation`

### ISSUE THREAD

**Issue by juliohm** [sefffal/PairPlots.jl#54]
And adding other types of correlations such as

`PairPlots.KendallCorrelation` via `StatsBase.corkendall`
`PairPlots.SpearmanCorrelation` via `StatsBase.corspearman`

In the future, if https://github.com/JuliaStats/StatsBase.jl/issues/934 gets solved, we can also add `PairPlots.ChatterjeeCorrelation`.

Also notice that the **stable docs** contain a typo that says that `PairPlots.Correlation() = PairPlots.Calculation(StatsBase.cov)`

**Comment by sefffal** [comment]
Thanks @juliohm for catching these! I agree this should be renamed. Instead of one type per function though, I would like to point out that you can already pass the function of your choice in, eg:
`PairPlots.Correlation(corspearman)`. The label in the plot will change accordingly.


As such, `Correlation` is really not a good name. It will accept any function of two variables. 


I would welcome suggestions for what to name this instead. Something like `PairwiseStat`?

**Comment by juliohm** [comment]
Thank you @sefffal for taking a look into it. I believe that `PairPlots.Pairwise(fun)` would be clear in this context? Do you plan to restrict the functionality to stats functions, or should it work with any pairwise function?

**Comment by sefffal** [comment]
Fixed in upcoming breaking release.
